import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import { SidebarNav } from '@/components/sidebar-nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SCARC - Sistema de Controle de Ar-Condicionado',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${inter.className} flex flex-col min-h-screen container`}
      >
        <Header />
        <div className="flex-1 grid md:grid-cols-[250px_1fr] md:gap-12">
          <div className="hidden md:block">
            <aside>
              <SidebarNav />
            </aside>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
